Truncate MAVLink 2 messages
mavlink/rust-mavlink pull request #122
Opened 2022-08-18 07:14 UTC by Erk-

The MAVLink documentation states the following[^1]:
> *MAVLink 2* implementations *must* truncate any empty (zero-filled)
> bytes at the end of the serialized payload before it is sent.

So this PR implements that.

[^1]: https://mavlink.io/en/guide/serialization.html#payload_truncation

2022-08-22 14:00 UTC, patrickelectric reviewed
Please squash the commits, I'll do some tests to validate the PR just to make sure.

2022-08-22 14:09 UTC, Erk- commented
I have rebased and squashed it, but it will likely need some minor changes when #124 is merged similar to the ones I have [here](https://github.com/fusion-engineering-forks/rust-mavlink/blob/fusion/mavlink-changes/build/util.rs#L22)

2022-08-22 17:54 UTC, patrickelectric requested changes

2022-08-22 17:54 UTC, patrickelectric commented on src/lib.rs
> +    fn ser_v1(&self) -> Vec<u8>;
Why not creating a `ser` function that receives as argument `MavlinkVersion` ? Like what we have for `deser`. The only difference of `ser_v1` and `ser_v2` is the trailing removal logic.

2022-08-22 17:54 UTC, patrickelectric commented on build/util.rs
> +        while let Some(&0) = #buf.last() {
Doing so we end up duplicating the same code again and again inside the binary, it's better to have a global function that abstract such behavior over having the same logic around every serialized message.

2022-08-22 17:54 UTC, patrickelectric commented on build/util.rs
> +        while let Some(&0) = #buf.last() {
To do that, we probably need to move this function to a library that will be used by all dialects.

2022-08-22 17:55 UTC, patrickelectric commented on build/util.rs
> +pub fn q_remove_trailing_zeroes(buf: proc_macro2::Ident) -> TokenStream {
What is the reason behind the q prefix ? That sounds unnecessary.

2022-08-23 13:53 UTC, patrickelectric approved these changes

2022-08-23 13:54 UTC, patrickelectric approved these changes
Thanks!

2022-08-23 13:54 UTC, merged