update clippy linting job
mavlink/rust-mavlink pull request #143
Opened 2022-11-29 15:48 UTC by danieleades

the old action is unsupported. This one will add inline comments to PRs. pretty.

question - what feature set should be enabled when performing clippy linting?

2022-11-30 11:40 UTC, patrickelectric requested changes
Thanks for the PR, please merge the development commits for us to merge the code.

2022-11-30 11:49 UTC, danieleades commented
> Thanks for the PR, please merge the development commits for us to merge the code.

I don't think this one's ready for the big time yet. See https://github.com/giraffate/clippy-action/issues/23

2022-12-02 06:15 UTC, danieleades commented
upstream github action has been fixed. Just waiting on a release, and then this will be ready for review

2022-12-02 06:25 UTC, danieleades commented
i take it back. the action is still escalating clippy warnings to hard build failures, just in a different way...

2023-10-24 18:30 UTC, closed without merging