Restructure project to enable custom mavlink bindings generation
mavlink/rust-mavlink pull request #223
Opened 2024-02-11 05:20 UTC by GrahamDennis

The goal of this PR is to enable generating Rust MAVLink bindings from custom MAVLink dialects in new crates.  This is done by splitting the project into three crates:

* mavlink-core: core MAVLink types including TCP, UDP and serial connections
* mavlink-bindgen: a library & CLI for generating Rust bindings for MAVLink dialects
* mavlink: generated MAVLink bindings for the MAVLink dialects in the mavlink/mavlink repo

mavlink-bindgen can be used to create MAVLink bindings for Rust, and this is used from `build.rs` in the `mavlink` crate to create bindings from the standard MAVLink dialects in https://github.com/mavlink/mavlink.

The `mavlink` crate is intended to remain API-compatible with the previous structure.

2024-02-17 02:49 UTC, GrahamDennis commented
This now passes all checks in my fork, so is ready for review @patrickelectric . The biggest change here is refactoring the crate into 3 crates in a single cargo workspace (which I think is required to supporting custom dialects). I'm happy to discuss alternative approaches or structures of a cargo workspace. Thanks!

2024-02-17 14:25 UTC, patrickelectric commented
That looks awesome, thanks @GrahamDennis. I'll review asap.

2024-02-17 22:38 UTC, patrickelectric requested changes
There is a mavlink-embedded binary lost in the PR.

2024-02-17 22:38 UTC, patrickelectric commented on mavlink/build/main.rs
> +use mavlink_bindgen;
is this import necessary ?

2024-02-18 01:43 UTC, GrahamDennis reviewed
I've also removed the accidentally-commited mavlink-embedded binary in the root directory.

2024-02-18 01:43 UTC, GrahamDennis commented on mavlink/build/main.rs
> +use mavlink_bindgen;
No, removed.

2024-02-18 15:41 UTC, patrickelectric approved these changes

2024-02-18 15:41 UTC, merged

2024-02-24 22:16 UTC, booo commented
This change broke two links in the main README to the examples.